maintainer       "Altoros Systems, Inc."
maintainer_email "pavel.pachkovskij@altoros.com"
license          "GPL-3"
description      "Installs/Configures Rack application"

version          "0.1"
name             "rack"
depends          "nginx"
depends          "juju"
depends          "nodejs"
