#!/bin/bash

set -eu

source "$(dirname $0)/common.sh"

cat >> '/etc/god/environment_variables.god' <<EOS
ENV['RAILS_ROOT'] = '$RAILS_ROOT'
ENV['RAILS_ENV'] = '$RAILS_ENV'
EOS

relation-set path="$root/config/*.god"