#!/bin/bash

set -eu

source "$(dirname $0)/common.sh"

host=`relation-get hostname`
port=`relation-get port`

exit_if_blank "$host" 'mongodb host'
exit_if_blank "$port" 'mongodb port'

configure_mongoid() {
  juju-log "Configure Mongoid"
  cat > "$root/config/mongoid.yml" <<EOS
$RAILS_ENV:
  sessions:
    default:
      database: "rails_${RAILS_ENV}"
      hosts:
        - ${host}:${port}
      options:
        consistency: :strong
EOS
}

configure_mongoid

create_mongoid_indexes

seed_database

compile_assets

requires_restart