#!/bin/bash

set -eu

source "$(dirname $0)/common.sh"

host=`relation-get host`
database=`relation-get database`
user=`relation-get user`
password=`relation-get password`

exit_if_blank "$host" 'mysql host'
exit_if_blank "$database" 'mysql database'
exit_if_blank "$user" 'mysql user'
exit_if_blank "$password" 'mysql password'

configure_database 'mysql2' "$database" "$host" "$user" "$password"

migrate_database

seed_database

compile_assets

requires_restart