#!/bin/bash

set -eux

source "$(dirname $0)/common.sh"
rakefile="$root/Rakefile"

tasks_loaded() {
  grep -q 'resque/tasks' $rakefile
}

tasks_loaded || echo "require 'resque/tasks'" >> $rakefile

mkdir -p ~/.vegas/resque-web