#!/bin/bash

set -eux

source "$(dirname $0)/common.sh"

resque_host=`relation-get hostname`
resque_port=`relation-get port`
resque_web_port=5678

exit_if_blank "$resque_host" 'resque host'
exit_if_blank "$resque_port" 'resque port'

configure_resque $resque_host $resque_port

open-port $resque_web_port

requires_restart